spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0

  redis:
    host: 10.211.55.3
    port: 6379
    password: 123456
   
  rabbitmq:
    host: 10.211.55.3
    port: 5672
    username: guest
    password: guest
